### ISSUE TITLE
unable to upload new symbols

### ISSUE THREAD

**Issue by ninapaley** [toolness/mystic-symbolic#73] opened 2021-04-02 21:04 UTC
Hey @toolness , these new symbols don't seem to pass tests when I upload them. Any idea why? atom.svg has some transparency, is that not allowed? 
[Archive.zip](https://github.com/toolness/mystic-symbolic/files/6251232/Archive.zip)
I labeled this "bug" but the bug may be on my end, I just don't know what it is...

**Comment by toolness** [comment] 2021-04-02 22:58
Hmm, it looks like the problem is with the `atom.svg` file you uploaded... it contains an [SVG radial gradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient) that the symbol importer isn't currently coded to support.  Are you using some kind of fancy fill style in Moho?  If you change that atom to just have simple fills then everything should work again, hopefully!

For now I have deleted the offending `atom.svg` file in 296da4fc9b7f584dfed1f7af50180bfa0f9f2c32 and the build seems to be working again.

**Comment by toolness** [comment] 2021-04-02 22:58
I'll close this issue for now but feel free to file a separate issue about supporting radial gradients in the symbol importer!

**Closed by toolness** 2021-04-02 22:58 UTC
Labels: bug
